[package]
name = "p2p-connection"
version = "0.1.0"
edition = "2024"

[dependencies]
quinn = { version = "0.11", default-features = false, features = ["rustls", "runtime-tokio"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
get_if_addrs = "0.5"
rcgen = "0.12"

